# Human-readable mod name, available for mcmod.info population.
modName = BetterQuesting

# Case-sensitive identifier string, available for mcmod.info population and used for automatic mixin JSON generation.
# Conventionally lowercase.
modId = betterquesting

# Root package of the mod, used to find various classes in other properties,
# mcmod.info substitution, enabling assertions in run tasks, etc.
group = betterquesting

minecraft_version=1.7.10
forge_version=10.13.4.1614-1.7.10
version=3.8.0

# A list of repositories to exclude from the includeWellKnownRepositories setting. Should be a space separated
# list of strings, with the acceptable keys being(case does not matter):
# cursemaven
# modrinth
excludeWellKnownRepositories =

# Optional parameter to customize the produced artifacts. Use this to preserve artifact naming when migrating older
# projects. New projects should not use this parameter.
customArchiveBaseName = BetterQuesting

systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=8891

systemProp.socksProxyHost=localhost
systemProp.socksProxyPort=1081
